const fs = require('fs');
let content = fs.readFileSync('app.js', 'utf8');

const replacements = {
  'Quais as áreas que você <span class=\\\'text-purple\\\'>mais quer perder gordura\\?</span>': '¿En qué áreas quieres <span class=\\\'text-purple\\\'>perder más grasa?</span>',
  'Toque nas áreas desejadas.': 'Toca las áreas deseadas.',
  '"Papada"': '"Papada"',
  '"Braços"': '"Brazos"',
  '"Barriga"': '"Barriga"',
  '"Cintura"': '"Cintura"',
  '"Glúteos"': '"Glúteos"',
  '"Coxas"': '"Muslos"',
  '"Corpo Todo"': '"Cuerpo Completo"',
  '"Ok, Vamos lá! 🚀"': '"¡Ok, vamos! 🚀"',
  '<span class=\\\'text-purple\\\'>Quantas gestações</span> você já teve\\?': '¿<span class=\\\'text-purple\\\'>Cuántos embarazos</span> has tenido?',
  'Isso ajuda a personalizar seu plano.': 'Esto ayuda a personalizar tu plan.',
  'Nunca estive grávida': 'Nunca estuve embarazada',
  '1 gestação': '1 embarazo',
  '2 gestações': '2 embarazos',
  '3 ou mais gestações': '3 o más embarazos',
  'Como é sua <span class=\\\'text-purple\\\'>rotina diária\\?</span>': '¿Cómo es tu <span class=\\\'text-purple\\\'>rutina diaria?</span>',
  'Selecione todas as que se encaixam.': 'Selecciona todas las que correspondan.',
  'Trabalho fora de casa': 'Trabajo fuera de casa',
  'Trabalho em home office': 'Hago home office',
  'Cuido da casa/família': 'Cuido la casa/familia',
  'Estudo': 'Estudio',
  'Quantas horas <span class=\\\'text-purple\\\'>você dorme por noite\\?</span>': '¿Cuántas horas <span class=\\\'text-purple\\\'>duermes por noche?</span>',
  'O sono é essencial para o emagrecimento.': 'El sueño es esencial para adelgazar.',
  'Menos de 5 horas': 'Menos de 5 horas',
  '5 a 7 horas': '5 a 7 horas',
  '7 a 9 horas': '7 a 9 horas',
  'Mais de 9 horas': 'Más de 9 horas',
  'Sim, eu me comprometo!': '¡Sí, me comprometo!',
  'Você se compromete a aplicar o <span class=\\\'text-purple\\\'>protocolo</span> por pelo menos 1 semana para poder ver os resultados\\?': '¿Te comprometes a aplicar el <span class=\\\'text-purple\\\'>protocolo</span> por al menos 1 semana para ver resultados?',
  'PARA LIBERAR SEU PLANO, PRECISO SABER:': 'PARA LIBERAR TU PLAN, NECESITO SABER:',
  'Sim me comprometo!': '¡Sí, me comprometo!',
  'Quero começar hoje': 'Quiero empezar hoy',
  'Não sei...': 'No lo sé...',
  'Resultado da sua <span class="text-purple">análise</span>': 'Resultado de tu <span class="text-purple">análisis</span>',
  'Seu IMC:': 'Tu IMC:',
  'Metabolismo desacelerado': 'Metabolismo desacelerado',
  'Risco de acúmulo de gordura visceral': 'Riesgo de acumulación de grasa visceral',
  'Hormônios de saciedade desregulados': 'Hormonas de saciedad desreguladas',
  'O segredo para secar:': 'El secreto para secar:',
  'ativar o GLP-1.': 'activar el GLP-1.',
  'é o "interruptor" hormonal natural!': 'es el "interruptor" hormonal natural!',
  'Benefícios da <span class="text-purple">Gelatina Mounjaro 👇</span>': 'Beneficios de la <span class="text-purple">Gelatina Mounjaro 👇</span>',
  'Receita 100% Natural': 'Receta 100% Natural',
  'Ativa o GLP-1 do seu corpo': 'Activa el GLP-1 de tu cuerpo',
  'Queima de Gordura localizada': 'Quema de grasa localizada',
  'Regula o seu Metabolismo': 'Regula tu Metabolismo',
  'Leveza e corpo Desinchado': 'Ligereza y cuerpo desinflamado',
  'Menos impulsos por doces': 'Menos impulsos por dulces',
  'Fácil de fazer e seguir': 'Fácil de hacer y seguir',
  'Perdi 12kg em 5 semanas!': '¡Perdí 12kg en 5 semanas!',
  'Maria, 32 anos - São Paulo': 'María, 32 años - Santiago',
  'Continuar🚀': 'Continuar 🚀',
  'Continuar': 'Continuar',
  'Como usar a <span class="text-purple font-bold" style="font-weight: 800;">Gelatina Mounjaro</span>': 'Cómo usar la <span class="text-purple font-bold" style="font-weight: 800;">Gelatina Mounjaro</span>',
  'Simples, prático e eficaz': 'Simple, práctico y eficaz',
  'Prepare a gelatina': 'Prepara la gelatina',
  'Receita simples do app': 'Receta simple de la app',
  'Consuma 2x ao dia': 'Consume 2 veces al día',
  'Manhã e antes de dormir': 'Mañana y antes de dormir',
  '>Manhã<': '>Mañana<',
  'Em jejum': 'En ayunas',
  '>Dia<': '>Día<',
  'Sem fome': 'Sin hambre',
  '>Noite<': '>Noche<',
  '>Antes de dormir<': '>Antes de dormir<',
  'Você havia começado<br>a assistir!': '¡Ya habías comenzado<br>a ver!',
  'Onde deseja continuar\\?': '¿Dónde deseas continuar?',
  '▶ Continuar Vendo': '▶ Continuar Viendo',
  '🔄 Assistir do Início': '🔄 Ver desde el Inicio',
  'Verificando seus dados...': 'Verificando tus datos...',
  'Analisando suas respostas': 'Analizando tus respuestas',
  'Calculando seu déficit calórico': 'Calculando tu déficit calórico',
  'Selecionando ingredientes ideias': 'Seleccionando ingredientes ideales',
  'Verificação concluída!': '¡Verificación concluida!',
  'Avaliando seu perfil corporal...': 'Evaluando tu perfil corporal...',
  'Analisando seu metabolismo...': 'Analizando tu metabolismo...',
  'Processando informações...': 'Procesando información...',
  'Perfil metabólico analisado': 'Perfil metabólico analizado',
  'Meta de peso calculada': 'Meta de peso calculada',
  'Compatibilidade verificada': 'Compatibilidad verificada',
  'Protocolo de 30 dias montado': 'Protocolo de 30 días creado',
  'Bônus exclusivos selecionados': 'Bonos exclusivos seleccionados',
  'Oferta especial preparada': 'Oferta especial preparada',
  'Aguarde enquanto finalizamos tudo para você...': 'Espera mientras preparamos todo para ti...',
  'Por favor, selecione pelo menos uma área.': 'Por favor, selecciona por lo menos un área.',
  'Plano da Gelatina de 30 dias foi': 'Plan de Gelatina de 30 días fue',
  'Gerado com Sucesso!': '¡Generado con Éxito!',
  'Ele é exclusivo e gerado só uma vez, não saia dessa página para não perdê-lo.': 'Es exclusivo y generado solo una vez, no salgas de esta página para no perderlo.',
  '>Antes<': '>Antes<',
  '>Depois<': '>Después<',
  'SEU PLANO EXCLUSIVO': 'TU PLAN EXCLUSIVO',
  '1 Mês de Tratamento': '1 Mes de Tratamiento',
  'seguindo o protocolo certinho, veja o que vai acontecer:': 'siguiendo el protocolo, mira lo que pasará:',
  '>SEMANA 1<': '>SEMANA 1<',
  '>SEMANA 2<': '>SEMANA 2<',
  '>SEMANA 3<': '>SEMANA 3<',
  '>SEMANA 4<': '>SEMANA 4<',
  'Desincha e primeiros resultados': 'Desinflamación y primeros resultados',
  'Perda de até': 'Pérdida de hasta',
  '>META<': '>META<',
  'Resultado esperado:': 'Resultado esperado:',
  'Gelatina Mounjaro \\+ APP Protocolo Completo': 'Gelatina Mounjaro + APP Protocolo Completo',
  'ACESSO VITALÍCIO': 'ACCESO VITALICIO',
  'Receita completa da Gelatina Mounjaro': 'Receta completa de la Gelatina Mounjaro',
  'Protocolo de 30 dias passo a passo': 'Protocolo de 30 días paso a paso',
  'Acesso ao Aplicativo Exclusivo': 'Acceso a la Aplicación Exclusiva',
  'Lista completa dos ingredientes': 'Lista completa de los ingredientes',
  'Dicas para acelerar resultados': 'Tips para acelerar los resultados',
  'Acesso vitalício ao app': 'Acceso vitalicio a la app',
  'BÔNUS: Dietas completas': 'BONO: Dietas completas',
  'BÔNUS: Receitas doces saudáveis': 'BONO: Recetas dulces saludables',
  'BÔNUS: Aulas em vídeo de pilates na parede': 'BONO: Videoclases de pilates en pared',
  'TUDO ISSO DE R\\$109,00': 'TODO ESTO DE $35.00',
  'POR APENAS': 'POR SOLO',
  'R\\$ 27': '$27',
  'Ou 6x de R\\$5,32': 'O 6x de $4.50',
  'QUERO COMEÇAR 🍓': 'QUIERO EMPEZAR 🍓',
  'Garantia de Reembolso': 'Garantía de Reembolso',
  'Todo produto é obrigado a dar no mínimo 7 dias de garantia, porem confiamos tanto na fórmula que oferecemos 30 dias corridos.': 'Todo producto debe dar mínimo 7 días de garantía, pero confiamos tanto en la fórmula que ofrecemos 30 días.',
  'Ou seja, se você não gostar ou não funcionar pra você, nós reembolsaremos cada centavo que você pagou, sem questionar.': 'Es decir, si no te gusta o no funciona para ti, te devolveremos cada centavo sin preguntar.',
  'Perguntas Frequentes': 'Preguntas Frecuentes',
  'A Gelatina Mounjaro realmente funciona\\?': '¿La Gelatina Mounjaro realmente funciona?',
  'Compra 100% segura • Garantia de 30 dias': 'Compra 100% segura • Garantía de 30 días',
  'Quanto tempo leva para ver resultados\\?': '¿Cuánto tiempo tarda en dar resultados?',
  'É seguro\\? Tem efeitos colaterais\\?': '¿Es seguro? ¿Tiene efectos secundarios?',
  'Como vou receber o protocolo\\?': '¿Cómo recibiré el protocolo?',
  'E se não funcionar pra mim\\?': '¿Y si no me funciona?',
  'O pagamento é seguro\\?': '¿El pago es seguro?',
  'Preciso comprar ingredientes caros\\?': '¿Necesito comprar ingredientes caros?',
  'Seu protocolo expira em:': 'Tu protocolo expira en:',
  'O questionário já foi respondido. Redirecionando...': 'El cuestionario ya fue respondido. Redirigiendo...',

};

for (const [key, value] of Object.entries(replacements)) {
  const regex = new RegExp(key, 'g');
  content = content.replace(regex, value);
}

fs.writeFileSync('app.js', content, 'utf8');
console.log('Traducao ok!!!');
